### ISSUE TITLE
TestDownloadArtifact

### ISSUE THREAD

**Issue by 030** [030/n3dr#29]
```
func TestDownloadArtifact(t *testing.T) {
	actualError := n.downloadArtifact("http://releasesoftwaremoreoften.com")
	expectedError := "HTTP exist?"

	if actualError.Error() != expectedError {
		t.Errorf("Error incorrect. Expected: %v. Actual: %v", expectedError, actualError)
	}
}
```

returns

```
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range

goroutine 47 [running]:
testing.tRunner.func1(0xc00026d500)
        /usr/local/go/src/testing/testing.go:830 +0x392
panic(0x70c7c0, 0x9ef6c0)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
nexus3-cli/cli.Nexus3.artifactName(0x76e168, 0x15, 0x767e86, 0x5, 0x768c6f, 0x8, 0x76b409, 0xe, 0x774405, 0x23, ...)
        /home/ben/dev/nexus3-cli/cli/cli.go:132 +0x347
nexus3-cli/cli.Nexus3.downloadArtifact(0x76e168, 0x15, 0x767e86, 0x5, 0x768c6f, 0x8, 0x76b409, 0xe, 0x774405, 0x23, ...)
        /home/ben/dev/nexus3-cli/cli/cli.go:140 +0x99
nexus3-cli/cli.TestDownloadArtifact(0xc00026d500)
        /home/ben/dev/nexus3-cli/cli/cli_test.go:140 +0x78
testing.tRunner(0xc00026d500, 0x781a20)
        /usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:916 +0x35a
FAIL    nexus3-cli/cli  63.468s
```

**Comment by 030** [comment]
Solved by GH-35
